model:
  type: inf-llm
  path: lmsys/longchat-7b-v1.5-32k
  block_size: 128
  fattn: false
  n_init: 32
  n_local: 2048
  topk: 31
  repr_topk: 32
  max_cached_block: 64
  exc_block_size: 512
  base: 500000
  distance_scale: 1.0

max_len: 2147483647
chunk_size: 8192
conv_type: longchat